development:
  password: 9a40d082c26f14a4823f2b91ed23055f
  theme_id: "162580361"
  store: somihan.myshopify.com

  ignore_files:
    - _assets/*
    - node_modules/*
    - .git/*
    - .gitignore
    - README.md
    - Gruntfile.js
    - package.json
    - tag_apis.liquid